name: The UBERginger
favicon: null
layout_spectrum: 0.8696674704551697
typography_spectrum: 0.3024580776691437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8100588710512966
  lightness: 0.285008990438655
  saturation: 0.09778577391989529
  rhythmicContrast: 0.782727048266679
purpose: []
